name = "PiPiMadrid"
uuid = "768ee2b6-c705-4f61-b10f-f525213ab444"
authors = ["Mikhail Mikhasenko <mikhail.mikhasenko@cern.ch>"]
version = "0.1.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Parameters = "0.12.0"
julia = "1.7"
